import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

console.log('seeding track DB...');

const tracks = [
  {
    trackId: 1,
    tapeId: 1,
    ragaId: 54,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'good',
    master: false,
    mediaTypeId: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1636225571/music/00001_ag4fgy.mp3',
  },
  {
    trackId: 2,
    tapeId: 1,
    ragaId: 213,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'good',
    master: false,
    mediaTypeId: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045222/music/00002_blpoqs.mp3',
  },
  {
    trackId: 3,
    tapeId: 2,
    ragaId: 306,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'NOT OK; Rasa: Viraha and Union',
    audioQuality: 'poor',
    master: true,
    mediaTypeId: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045635/music/00003_xo50fm.mp3',
  },
  {
    trackId: 4,
    tapeId: 2,
    ragaId: 72,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'OK; Rasa: Viraha and Bhakti',
    audioQuality: 'poor',
    master: true,
    mediaTypeId: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045878/music/00004_qs35fm.mp3',
  },
  {
    trackId: 5,
    tapeId: 3,
    ragaId: 270,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: true,
    mediumGat: false,
    fastGat: true,
    accompanied: false,
    audioQuality: 'good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640063707/music/00005_kadp5e.mp3',
  },
  {
    trackId: 6,
    tapeId: 3,
    ragaId: 270,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: true,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640063714/music/00006_kspnkk.mp3',
  },
  {
    trackId: 7,
    tapeId: 4,
    ragaId: 235,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'good',
    master: false,
    mediaTypeId: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045617/music/00007_nsjnnz.mp3',
  },
  {
    trackId: 8,
    tapeId: 4,
    ragaId: 137,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'good',
    master: false,
    mediaTypeId: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045655/music/00008_iw2lzk.mp3',
  },
  {
    trackId: 9,
    tapeId: 5,
    ragaId: 213,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'poor',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045668/music/00009_zjkdbp.mp3',
  },
  {
    trackId: 10,
    tapeId: 5,
    ragaId: 103,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: true,
    mediumGat: false,
    fastGat: false,
    accompanied: true,
    audioQuality: 'poor',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045578/music/00010_xwelro.mp3',
  },
  {
    trackId: 11,
    tapeId: 5,
    ragaId: 24,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: true,
    mediumGat: false,
    fastGat: false,
    accompanied: true,
    audioQuality: 'poor',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045634/music/00011_tqcvvh.mp3',
  },
  {
    trackId: 12,
    tapeId: 5,
    ragaId: 103,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: false,
    mediumGat: true,
    fastGat: false,
    accompanied: true,
    audioQuality: 'poor',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045538/music/00012_jbbnm4.mp3',
  },
  {
    trackId: 13,
    tapeId: 5,
    ragaId: 103,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: false,
    mediumGat: true,
    fastGat: false,
    accompanied: true,
    notes: 'Dhun #3. Arjun notes: Resembles ragas Malgunji, Manjh Khamaj',
    audioQuality: 'poor',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045547/music/00013_zaersn.mp3',
  },
  {
    trackId: 14,
    tapeId: 6,
    ragaId: 356,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: true,
    accompanied: true,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679448/music/00014_zcfnrq.mp3',
  },
  {
    trackId: 15,
    tapeId: 6,
    ragaId: 72,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679366/music/00015_us5mzf.mp3',
  },
  {
    trackId: 16,
    tapeId: 6,
    ragaId: 188,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: false,
    slowGat: false,
    mediumGat: false,
    fastGat: true,
    accompanied: true,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679368/music/00016_y0ptll.mp3',
  },
  {
    trackId: 17,
    tapeId: 7,
    ragaId: 356,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: true,
    mediumGat: false,
    fastGat: true,
    accompanied: true,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679479/music/00017_l2bqih.mp3',
  },
  {
    trackId: 18,
    tapeId: 7,
    ragaId: 188,
    primaryArtistId: 1,
    alap: true,
    jor: false,
    jhalla: false,
    slowGat: true,
    mediumGat: false,
    fastGat: true,
    accompanied: true,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679385/music/00018_dxyu1l.mp3',
  },
  {
    trackId: 19,
    tapeId: 8,
    ragaId: 178,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679327/music/00019_jizicf.mp3',
  },
  {
    trackId: 20,
    tapeId: 8,
    ragaId: 225,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679361/music/00020_ykotvg.mp3',
  },
  {
    trackId: 21,
    tapeId: 9,
    ragaId: 364,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679921/music/00021_evonla.mp3',
  },
  {
    trackId: 22,
    tapeId: 9,
    ragaId: 16,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679900/music/00022_lbg7ka.mp3',
  },
  {
    trackId: 23,
    tapeId: 10,
    ragaId: 128,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679877/music/00023_uhruod.mp3',
  },
  {
    trackId: 24,
    tapeId: 10,
    ragaId: 8,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650681293/music/00024_bnf66f.mp3',
  },
  {
    trackId: 25,
    tapeId: 11,
    ragaId: 302,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679930/music/00025_y8eqih.mp3',
  },
  {
    trackId: 26,
    tapeId: 11,
    ragaId: 188,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679837/music/00026_y2vnnt.mp3',
  },
  {
    trackId: 27,
    tapeId: 12,
    ragaId: 72,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679841/music/00027_eohbys.mp3',
  },
  {
    trackId: 28,
    tapeId: 13,
    ragaId: 55,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679851/music/00028_tonhm9.mp3',
  },
  {
    trackId: 29,
    tapeId: 13,
    ragaId: 78,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679861/music/00029_oh9bl3.mp3',
  },
  {
    trackId: 30,
    tapeId: 14,
    ragaId: 72,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'Alap/Jor/Jhalla',
    audioQuality: "Need to figure out what's going on in this track",
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650679919/music/00030_zofjnk.mp3',
  },
  {
    trackId: 31,
    tapeId: 14,
    ragaId: 72,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: true,
    mediumGat: false,
    fastGat: true,
    accompanied: true,
    notes: 'Gat',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650680467/music/00031_oo7adz.mp3',
  },
  {
    trackId: 32,
    tapeId: 14,
    ragaId: 366,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'Alap/Jor/Jhalla',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650680442/music/00032_itnrve.mp3',
  },
  {
    trackId: 33,
    tapeId: 14,
    ragaId: 366,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: false,
    mediumGat: true,
    fastGat: false,
    accompanied: true,
    notes: 'Gat',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650680423/music/00033_td44cq.mp3',
  },
  {
    trackId: 34,
    tapeId: 15,
    ragaId: 128,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650680454/music/00034_jb6oww.mp3',
  },
  {
    trackId: 35,
    tapeId: 15,
    ragaId: 86,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650680484/music/00035_mk7gkf.mp3',
  },
  {
    trackId: 36,
    tapeId: 16,
    ragaId: 197,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'Swarmandala',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650680465/music/00036_vulne6.mp3',
  },
  {
    trackId: 37,
    tapeId: 16,
    ragaId: 367,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'singing with tanpura',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650680454/music/00037_vcis3o.mp3',
  },
  {
    trackId: 38,
    tapeId: 16,
    ragaId: 235,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'Swarmandala',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650680468/music/00038_n3bwcc.mp3',
  },
  {
    trackId: 39,
    tapeId: 17,
    ragaId: 239,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: '',
  },
  {
    trackId: 40,
    tapeId: 17,
    ragaId: 366,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: '',
  },
  {
    trackId: 41,
    tapeId: 18,
    ragaId: 368,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: true,
    fastGat: true,
    accompanied: true,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650680477/music/00041_ltbatr.mp3',
  },
  {
    trackId: 42,
    tapeId: 18,
    ragaId: 363,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: '',
  },
  {
    trackId: 43,
    tapeId: 19,
    ragaId: 356,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: true,
    mediumGat: false,
    fastGat: true,
    accompanied: true,
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650736016/music/00043_acsxsj.mp3',
  },
  {
    trackId: 44,
    tapeId: 19,
    ragaId: 363,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'Tabla solo',
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650735925/music/00044_io337g.mp3',
  },
  {
    trackId: 45,
    tapeId: 19,
    ragaId: 159,
    primaryArtistId: 1,
    alap: true,
    jor: false,
    jhalla: false,
    slowGat: true,
    mediumGat: false,
    fastGat: true,
    accompanied: true,
    notes: 'MAY NEED TO GET SPLIT UP',
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650736054/music/00045_jb45h5.mp3',
  },
  {
    trackId: 46,
    tapeId: 19,
    ragaId: 103,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: '',
  },
  {
    trackId: 47,
    tapeId: 20,
    ragaId: 302,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650736061/music/00047_fynt21.mp3',
  },
  {
    trackId: 48,
    tapeId: 20,
    ragaId: 72,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650735990/music/00048_eimof2.mp3',
  },
  {
    trackId: 49,
    tapeId: 21,
    ragaId: 302,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Good',
    master: true,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650736066/music/00049_kqie4t.mp3',
  },
  {
    trackId: 50,
    tapeId: 22,
    ragaId: 279,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'Chanting at the end',
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650736039/music/00050_xekw36.mp3',
  },
  {
    trackId: 51,
    tapeId: 22,
    ragaId: 134,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'Chanting at the end',
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737220/music/00051_rwoygx.mp3',
  },
  {
    trackId: 52,
    tapeId: 23,
    ragaId: 137,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737129/music/00052_wqerk2.mp3',
  },
  {
    trackId: 53,
    tapeId: 23,
    ragaId: 235,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737129/music/00052_wqerk2.mp3',
  },
  {
    trackId: 54,
    tapeId: 24,
    ragaId: 365,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'Chanting Mantras',
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650736935/music/00054_zknu0h.mp3',
  },
  {
    trackId: 55,
    tapeId: 24,
    ragaId: 54,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737241/music/00055_piwd00.mp3',
  },
  {
    trackId: 56,
    tapeId: 24,
    ragaId: 188,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737187/music/00056_cjakf7.mp3',
  },
  {
    trackId: 57,
    tapeId: 25,
    ragaId: 78,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737293/music/00057_o7jbih.mp3',
  },
  {
    trackId: 58,
    tapeId: 25,
    ragaId: 72,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737282/music/00058_jj0ym0.mp3',
  },
  {
    trackId: 59,
    tapeId: 26,
    ragaId: 356,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737267/music/00059_ia95ao.mp3',
  },
  {
    trackId: 60,
    tapeId: 26,
    ragaId: 235,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737197/music/00060_jkjeuc.mp3',
  },
  {
    trackId: 61,
    tapeId: 27,
    ragaId: 131,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: false,
    slowGat: false,
    mediumGat: true,
    fastGat: false,
    accompanied: true,
    notes: 'Confirm tape number correct',
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737073/music/00061_wo5ixx.mp3',
  },
  {
    trackId: 62,
    tapeId: 27,
    ragaId: 103,
    primaryArtistId: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slowGat: false,
    mediumGat: true,
    fastGat: false,
    accompanied: true,
    notes: 'Confirm tape # correct',
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650736919/music/00062_ojouel.mp3',
  },
  {
    trackId: 63,
    tapeId: 28,
    ragaId: 328,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737288/music/00063_wli0an.mp3',
  },
  {
    trackId: 64,
    tapeId: 28,
    ragaId: 8,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    notes: 'Sharing afterward',
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737305/music/00064_vy15h2.mp3',
  },
  {
    trackId: 65,
    tapeId: 29,
    ragaId: 75,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737183/music/00065_ksztiw.mp3',
  },
  {
    trackId: 66,
    tapeId: 29,
    ragaId: 75,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: true,
    mediumGat: false,
    fastGat: true,
    accompanied: true,
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737088/music/00066_kmjqem.mp3',
  },
  {
    trackId: 67,
    tapeId: 29,
    ragaId: 103,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: true,
    fastGat: false,
    accompanied: true,
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650736929/music/00067_ohf3bn.mp3',
  },
  {
    trackId: 68,
    tapeId: 30,
    ragaId: 72,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737059/music/00068_jbwrby.mp3',
  },
  {
    trackId: 69,
    tapeId: 31,
    ragaId: 137,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737216/music/00069_emnlfu.mp3',
  },
  {
    trackId: 70,
    tapeId: 31,
    ragaId: 197,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737189/music/00070_rv33a8.mp3',
  },
  {
    trackId: 71,
    tapeId: 32,
    ragaId: 78,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Fair',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737285/music/00071_ugsxbj.mp3',
  },
  {
    trackId: 72,
    tapeId: 33,
    ragaId: 188,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: false,
    fastGat: false,
    accompanied: false,
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737196/music/00072_gczsax.mp3',
  },
  {
    trackId: 73,
    tapeId: 34,
    ragaId: 302,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: false,
    mediumGat: true,
    fastGat: true,
    accompanied: true,
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737274/music/00073_gncr6i.mp3',
  },
  {
    trackId: 74,
    tapeId: 34,
    ragaId: 188,
    primaryArtistId: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slowGat: true,
    mediumGat: false,
    fastGat: true,
    accompanied: true,
    audioQuality: 'Good',
    master: false,
    mediaTypeId: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1650737274/music/00074_rtvgmg.mp3',
  },
];

async function main() {
  tracks.forEach(async (track) => {
    await prisma.track.create({
      data: track,
    });
  });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
