const { Track } = require('../models');

const trackData = [
  {
    tape_id: 1,
    raga_id: 48,
    primary_artist_id: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slow_gat: false,
    medium_gat: false,
    fast_gat: false,
    accompanied: false,
    notes: '',
    audio_quality: 'good',
    master: false,
    media_type_id: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1636225571/music/00001_ag4fgy.mp3',
  },
  {
    tape_id: 1,
    raga_id: 362,
    primary_artist_id: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slow_gat: false,
    medium_gat: false,
    fast_gat: false,
    accompanied: false,
    notes: '',
    audio_quality: 'good',
    master: false,
    media_type_id: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045222/music/00002_blpoqs.mp3',
  },
  {
    tape_id: 2,
    raga_id: 253,
    primary_artist_id: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slow_gat: false,
    medium_gat: false,
    fast_gat: false,
    accompanied: false,
    notes: 'NOT OK; Rasa: Viraha and Union',
    audio_quality: 'poor',
    master: true,
    media_type_id: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045635/music/00003_xo50fm.mp3',
  },
  {
    tape_id: 2,
    raga_id: 62,
    primary_artist_id: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slow_gat: false,
    medium_gat: false,
    fast_gat: false,
    accompanied: false,
    notes: 'OK; Rasa: Viraha and Bhakti',
    audio_quality: 'poor',
    master: true,
    media_type_id: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045878/music/00004_qs35fm.mp3',
  },
  {
    tape_id: 3,
    raga_id: 223,
    primary_artist_id: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slow_gat: true,
    medium_gat: false,
    fast_gat: true,
    accompanied: false,
    notes: '',
    audio_quality: 'good',
    master: false,
    media_type_id: 1,
    public: false,
    url: '/static/media/00005.a9f0fd86.mp3',
  },
  {
    tape_id: 3,
    raga_id: 223,
    primary_artist_id: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slow_gat: true,
    medium_gat: false,
    fast_gat: false,
    accompanied: false,
    notes: '',
    audio_quality: 'good',
    master: false,
    media_type_id: 1,
    public: false,
    url: '/static/media/00006.c814dfcf.mp3',
  },
  {
    tape_id: 4,
    raga_id: 192,
    primary_artist_id: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slow_gat: false,
    medium_gat: false,
    fast_gat: false,
    accompanied: false,
    notes: '',
    audio_quality: 'good',
    master: false,
    media_type_id: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045617/music/00007_nsjnnz.mp3',
  },
  {
    tape_id: 4,
    raga_id: 115,
    primary_artist_id: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slow_gat: false,
    medium_gat: false,
    fast_gat: false,
    accompanied: false,
    notes: '',
    audio_quality: 'good',
    master: false,
    media_type_id: 1,
    public: true,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045655/music/00008_iw2lzk.mp3',
  },
  {
    tape_id: 5,
    raga_id: 362,
    primary_artist_id: 1,
    alap: true,
    jor: true,
    jhalla: true,
    slow_gat: false,
    medium_gat: false,
    fast_gat: false,
    accompanied: false,
    notes: '',
    audio_quality: 'poor',
    master: false,
    media_type_id: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045668/music/00009_zjkdbp.mp3',
  },
  {
    tape_id: 5,
    raga_id: 303,
    primary_artist_id: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slow_gat: true,
    medium_gat: false,
    fast_gat: false,
    accompanied: true,
    notes: '',
    audio_quality: 'poor',
    master: false,
    media_type_id: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045578/music/00010_xwelro.mp3',
  },
  {
    tape_id: 5,
    raga_id: 21,
    primary_artist_id: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slow_gat: true,
    medium_gat: false,
    fast_gat: false,
    accompanied: true,
    notes: '',
    audio_quality: 'poor',
    master: false,
    media_type_id: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045634/music/00011_tqcvvh.mp3',
  },
  {
    tape_id: 5,
    raga_id: 303,
    primary_artist_id: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slow_gat: false,
    medium_gat: true,
    fast_gat: false,
    accompanied: true,
    notes: '',
    audio_quality: 'poor',
    master: false,
    media_type_id: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045538/music/00012_jbbnm4.mp3',
  },
  {
    tape_id: 5,
    raga_id: 303,
    primary_artist_id: 1,
    alap: false,
    jor: false,
    jhalla: false,
    slow_gat: false,
    medium_gat: true,
    fast_gat: false,
    accompanied: true,
    notes: '',
    audio_quality: 'poor',
    master: false,
    media_type_id: 1,
    public: false,
    url: 'https://res.cloudinary.com/intelly/video/upload/v1640045547/music/00013_zaersn.mp3',
  },
];

const seedTracks = () => Track.bulkCreate(trackData);

module.exports = seedTracks;
